services:
  - type: web
    name: cooking-assistant
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port 10000
    envVars:
      - key: PORT
        value: 10000
    buildFilter:
      paths:
        - requirements.txt
        - app.py
        - Aptfile
    autoDeploy: true
